### ISSUE TITLE
Declarations Consistency

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/DavidK#2]
https://github.com/CodingDojo-MEAN-06-18/DavidK/blob/3e0a10a597fd8c4b5f1835545ba622f3b2f1e726/weekFour/Quoting_Dojo/server.js#L29-L46

I like the `Object` destructuring with your Schema. I do recommend that you be consistent with your variable declarations. If you're using `const/let` don't use `var` at all.

**Comment by dkang417** [comment]
thanks for the feedback Jason.  .will def try to remember that for the
future!

have a great weekend!

-David
